trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: serviceConnection
    type: string

  - name: acrName
    type: string

  - name: vaultName
    type: string

  - name: storageName
    type: string

steps:
  - task: PowerShell@2
    displayName: "Set Pipeline Host's IP Address"
    inputs:
      targetType: inline
      script: |        
        $ip = @(Invoke-WebRequest http://ifconfig.me/ip).Content

        Write-Host "##vso[task.setvariable variable=PIPELINE_HOST_IP_ADDRESS;]${ip}"
        Write-Host "Pipeline host's ip: name = PIPELINE_HOST_IP_ADDRESS, ip address = $ip"

  # Container Registry
  - task: AzureCLI@2
    displayName: "Add the host machine's IP to access the Container Registry"
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az acr network-rule add -n ${{ parameters.acrName }} --ip-address "$(PIPELINE_HOST_IP_ADDRESS)"

  - task: AzureCLI@2
    displayName: "Delete the host machine's IP to access the Container Registry"
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az acr network-rule remove -n ${{ parameters.acrName }} --ip-address "$(PIPELINE_HOST_IP_ADDRESS)"

  # Key Vault
  - task: AzureCLI@2
    displayName: "Add the host machine's IP to access the Key Vault"
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az keyvault network-rule add --name ${{ parameters.vaultName }} --ip-address "$(PIPELINE_HOST_IP_ADDRESS)"

  - task: AzureCLI@2
    displayName: "Delete the host machine's IP to access the Key Vault"
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az keyvault network-rule remove --name ${{ parameters.vaultName }} --ip-address "$(PIPELINE_HOST_IP_ADDRESS)"

  # Storage Account
  - task: AzureCLI@2
    displayName: "Allowing the host machine's IP to access the Storage Account"
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az storage account network-rule add --account-name ${{ parameters.storageName }} --ip-address "$(PIPELINE_HOST_IP_ADDRESS)"

  - task: AzureCLI@2
    displayName: "Unallowing the host machine's IP to access the Storage Account"
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az storage account network-rule remove -account-name ${{ parameters.storageName }} --ip-address "$(PIPELINE_HOST_IP_ADDRESS)"